CREATE DATABASE SENAI_HROADS_TARDE

USE SENAI_HROADS_TARDE

CREATE TABLE CLASSES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TIPO_HABILIDADE(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE HABILIDADE(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,ID_TIPO_HABIL INT NOT NULL FOREIGN KEY REFERENCES TIPO_HABILIDADE(ID)
);

CREATE TABLE CLASSE_HABILIDADE(
	ID_CLASSE INT NOT NULL FOREIGN KEY REFERENCES CLASSES(ID)
	,ID_HABILIDADE INT NOT NULL FOREIGN KEY REFERENCES HABILIDADE(ID)
);

CREATE TABLE PERSONAGENS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,ID_CLASSE INT NOT NULL FOREIGN KEY REFERENCES CLASSES(ID)
	,VIDA_MAXIMA TINYINT NOT NULL
	,MANA_MAXIMA TINYINT NOT NULL
	,DATA_ATUALIZACAO DATE NOT NULL
	,DATA_CRIACAO DATE NOT NULL
);