UPDATE PERSONAGENS SET NOME = 'Fer7' WHERE ID = 3

UPDATE CLASSES SET NOME = 'NECROMANCER' WHERE ID = 5

SELECT * FROM PERSONAGENS

SELECT * FROM CLASSES ORDER BY ID

SELECT NOME FROM CLASSES

SELECT * FROM HABILIDADE

SELECT COUNT(*) FROM HABILIDADE

SELECT ID FROM HABILIDADE ORDER BY ID ASC

SELECT * FROM HABILIDADE

SELECT * FROM HABILIDADE INNER JOIN TIPO_HABILIDADE ON HABILIDADE.ID_TIPO_HABIL = TIPO_HABILIDADE.ID

SELECT * FROM PERSONAGENS INNER JOIN CLASSES ON PERSONAGENS.ID_CLASSE = CLASSES.ID

SELECT * FROM PERSONAGENS RIGHT JOIN CLASSES ON PERSONAGENS.ID_CLASSE = CLASSES.ID

SELECT * FROM CLASSES INNER JOIN CLASSE_HABILIDADE ON CLASSES.ID = CLASSE_HABILIDADE.ID_CLASSE INNER JOIN HABILIDADE ON HABILIDADE.ID = CLASSE_HABILIDADE.ID_HABILIDADE

SELECT * FROM HABILIDADE INNER JOIN CLASSE_HABILIDADE ON HABILIDADE.ID = CLASSE_HABILIDADE.ID_CLASSE RIGHT JOIN CLASSES ON CLASSES.ID = CLASSE_HABILIDADE.ID_HABILIDADE
